server:
  port: 8040

spring:
  config:
    import: optional:configserver:http://${CONFIG_SERVER:localhost}:8888
  application:
    name: fulfillment-service
  kafka:
    consumer:
      group-id: FULFILLMENT
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.type.mapping: "Order:com.sytoss.ecommerce.platform.fulfillmentservice.model.order.Order"
    topics:
      input-library: ORDERS