server:
  port: 8000
  forward-headers-strategy: framework

spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://${CONFIG_SERVER:localhost}:8888
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update