server:
  port: 8000

spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/user-db
    username: admin
    password: admin
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
