server:
  port: 8000

spring:
  application:
    name: user-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/user-db
    username: root
    password: admin
