server:
  port: 8020
  forward-headers-strategy: framework

spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: "Order:com.sytoss.ecommerce.platform.orderservice.model.Order"
    topics:
      input-library: ORDERS