server:
  port: 8020

spring:
  application:
    name: order-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: order-db
      username: root
      password: admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka