server:
  port: 8010

spring:
  application:
    name: product-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/product-db
    username: root
    password: admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
