server:
  port: 8030

spring:
  application:
    name: inventory-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/inventory-db
    username: root
    password: admin
