server:
  port: 8030

spring:
  application:
    name: inventory-service
  config:
    import: optional:configserver:http://localhost:8888
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update